services:

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: dbDevelop
      POSTGRES_USER: userDevelop
      POSTGRES_PASSWORD: postgres      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: